package pxf.toolkit.components.model.decorator;

/**
 * @author potatoxf
 * @date 2021/3/31
 */
public enum TableDecoratorStyle {
  /** 默认 */
  DEFAULT,
  /** 水平类型 */
  HORIZONTAL_LEFT,
  HORIZONTAL_CENTER,
  HORIZONTAL_RIGHT,

  /** 垂直类型 */
  VERTICAL_TOP,
  VERTICAL_MIDDLE,
  VERTICAL_BOTTOM,

  /** 边框类型 */
  BORDER_NONE,
  BORDER_THIN,
  BORDER_MEDIUM,
  BORDER_DASHED,
  BORDER_DOTTED,
  BORDER_THICK,
  BORDER_DOUBLE,
  BORDER_HAIR,
  BORDER_MEDIUM_DASHED,
  BORDER_DASH_DOT,
  BORDER_MEDIUM_DASH_DOT,
  BORDER_DASH_DOT_DOT,
  BORDER_MEDIUM_DASH_DOT_DOT,
  BORDER_SLANTED_DASH_DOT,

  /** 下划线内容 */
  UNDERLINE_SINGLE,
  UNDERLINE_DOUBLE,
  UNDERLINE_SINGLE_ACCOUNTING,
  UNDERLINE_DOUBLE_ACCOUNTING,
}
